# Generated by Django 5.2.7 on 2025-10-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='f_name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='l_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
